### ISSUE TITLE
Check for special characters in a string

### ISSUE THREAD

**Issue by patil-ashutosh** [patil-ashutosh/go-regex-utility#11]
**Description**

- Add Method which checks  for special characters in string, return true if special character are present in string else return false.  
- Special characters ->  (/*-+_@&$#%) 
- Method can be added in rstring/string.go file

**Acceptance Criteria**
- [ ]  Add Unit Tests

- [ ] Add Documentaion

This repository is valid for HacktoberFest2020

Read before making PR - How to contribute on Github

**Comment by thegalang** [comment]
I can do this

**Comment by ryanvarghese** [comment]
hey @patil-ashutosh i would to love work on this . Can you please assign this to me?

**Comment by binkkatal** [comment]
@patil-ashutosh pushed a PR
https://github.com/patil-ashutosh/go-regex-utility/pull/12

**Comment by patil-ashutosh** [comment]
> I can do this

@thegalang feel free to open PR,  as these are hactoberfest issues

**Comment by patil-ashutosh** [comment]
> hey @patil-ashutosh i would to love work on this . Can you please assign this to me?

@ryanvarghese  feel free to open PR
