### ISSUE TITLE
Remove non-alphanumeric characters

### ISSUE THREAD

**Issue by patil-ashutosh** [patil-ashutosh/go-regex-utility#18]
**Description**

Remove all characters from a string which are not in a-z A-Z 0-9  using regex

- Method can be added in rstring/string.go file

**Acceptance Criteria**

- Add Unit Tests
- Add Documentaion

This repository is valid for HacktoberFest2020

Read before making PR - How to contribute on Github
#### Note: Feel free to open PR as these PR will be counted for hactoberfest acceptence

**Comment by Norbinsh** [comment]
hi @patil-ashutosh, may I work on this?
