### ISSUE TITLE
Validate an IPv6 Address

### ISSUE THREAD

**Issue by patil-ashutosh** [patil-ashutosh/go-regex-utility#23]
**Description**
1) What is valid IPv6 criterion?
2) Create method to validate IPv6

- Method can be added in rvalidation package 

**Acceptance Criteria**

- Add Unit Tests
- Add Documentaion

This repository is valid for HacktoberFest2020

Read before making PR - How to contribute on Github

**Comment by pradeepnnv** [comment]
I would like to give this a try.
