### ISSUE TITLE
Validate the date format in "dd/mm/yyyy"

### ISSUE THREAD

**Issue by patil-ashutosh** [patil-ashutosh/go-regex-utility#24]
**Description**
1) Validate the date format in "dd/mm/yyyy"
2) Create method to validate date format 
3) Examples 
_i) Date: 1/14/2018 -> false
ii) Date: 31/07/2010 -> true_

- Method can be added in rvalidation package 

**Acceptance Criteria**

- Add Unit Tests
- Add Documentaion

This repository is valid for HacktoberFest2020

Read before making PR - How to contribute on Github

**Comment by souvikmaji** [comment]
Hey can i pick this up?

**Comment by patil-ashutosh** [comment]
> Hey can i pick this up?

@souvikmaji go ahead
